version: "3.7"

services:
  dev-db:
    image: postgres:16.1-alpine3.19
    container_name: dev-db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - internal

  db_dashboard:
    image: adminer
    container_name: db_dashboard
    restart: always
    ports:
      - 8081:8080
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal: